version: '3'
services:
  fastapi-service:
    container_name: fastapi-service
    restart: always
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./.env:/app/.env
    ports:
      - '8080:8080' # Change 8080 to your port
    env_file:
      - ./.env

    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           device_ids: ['0'] # Change this to your GPU ID
    #           capabilities: [gpu]
